name: pickuplines
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.13.0
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_gen: ^5.10.0
  intl_translation: ^0.20.1
  path_provider: ^2.1.5
  logger_screen: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/data/
    - assets/data/home/
    - assets/data/firstline/
    - assets/data/firstline/flirt_first_line.json
    - assets/icon/
    - assets/icon/icons.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icons.jpg"
