// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUDdYqN8RD5o1omvOQrMnWDpiZji18DY',
    appId: '1:311959562953:web:42d27de487b1c7e83bfb18',
    messagingSenderId: '311959562953',
    projectId: 'flirt-lines',
    authDomain: 'flirt-lines.firebaseapp.com',
    storageBucket: 'flirt-lines.firebasestorage.app',
    measurementId: 'G-RWLTS9H0NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_3DiTWp8EaQJ5NPRaQgj4fyyoLcjvZ8',
    appId: '1:311959562953:android:990997ec12b78dc33bfb18',
    messagingSenderId: '311959562953',
    projectId: 'flirt-lines',
    storageBucket: 'flirt-lines.firebasestorage.app',
    authDomain: 'flirt-lines.firebaseapp.com',
    androidClientId: '311959562953-sample.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVx-cm2PFNWgzN6C1JFBdw6bomtIwkgmU',
    appId: '1:311959562953:ios:05157e31aa3cb6a63bfb18',
    messagingSenderId: '311959562953',
    projectId: 'flirt-lines',
    storageBucket: 'flirt-lines.firebasestorage.app',
    iosBundleId: 'com.example.pickuplines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVx-cm2PFNWgzN6C1JFBdw6bomtIwkgmU',
    appId: '1:311959562953:ios:05157e31aa3cb6a63bfb18',
    messagingSenderId: '311959562953',
    projectId: 'flirt-lines',
    storageBucket: 'flirt-lines.firebasestorage.app',
    iosBundleId: 'com.example.pickuplines',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUUDdYqN8RD5o1omvOQrMnWDpiZji18DY',
    appId: '1:311959562953:web:ac8ad587c9b856243bfb18',
    messagingSenderId: '311959562953',
    projectId: 'flirt-lines',
    authDomain: 'flirt-lines.firebaseapp.com',
    storageBucket: 'flirt-lines.firebasestorage.app',
    measurementId: 'G-3XNQ0Y9WEK',
  );
}
